### ISSUE TITLE
Some improvements

### ISSUE THREAD

**Issue by igarrido-adalab** [Adalab/modulo-2-evaluacion-intermedia-maialenmunoa#1]
Really cool job @maialenmunoa !!!

Here you have some tips about your exercise:

- It's a good practice to make multiple commits as you work. 
- Improve the structure of your web files (CSS and JS) starting their paths with `./` in the HTML.

### Further challenges

Then you can improve the game as you please, here you have some ideas:

- Add a reset button that cleans the tries counter, generates a new random number and writes the initial feedback. 
- Show the restart game button when the game is over and hide the test button. 
- Complete the code needed for the restart game button. 
- Add a limit for the numbre of tries. If the user reaches that limit, the page announces that "The game is over". 
- Whatever you want!

### Call to action

Let me know if you have any doubts ;)

Go for it!!

> From now on you can commit your changes to the main branch of your project.
> Do not close this issue until your teacher asks you to

**Comment by maialenmunoa** [comment]
Thank you for your feedback @igarrido-adalab 😉

**Comment by maialenmunoa** [comment]
Hello @igarrido-adalab,

How are you doing? 

I have made some improvements:

- Added reset button
- Added limit of moves to 10
- Empty the input when the game ends
- Added show random number when you lose
- 
I look forward to your comments!!!!

**Comment by igarrido-adalab** [comment]
It looks marvellous!
